AWSTemplateFormatVersion: '2010-09-09'
Description: starterproject-Ritvik microservice.

Parameters:
  ServiceName:
    Type: String
  StageName:
    Type: String
  CodeBucketName:
    Type: String
  CodeKey:
    Type: String
  SwaggerKey:
    Type: String
  EnvironmentType:
    Description: Environment type.
    Type: String
    AllowedValues: [prod, dev]
    ConstraintDescription: must specify prod or dev.

Conditions:
  UseProdCondition:
    !Equals [!Ref EnvironmentType, prod]

Resources:
  ##########################################################################################
  # Shared Resources / Roles
  ##########################################################################################
  starterprojectBaseRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        - PolicyName: "AssumeCrossAccountLoggingRole"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: "Allow"
              Action:
              - 'sts:AssumeRole'
              Resource: arn:aws:iam::405028608951:role/us-east-1-LoggingCrossAccount


  ##########################################################################################
  # API Gateway configuration
  ##########################################################################################
  Api:
    Type: AWS::ApiGateway::RestApi
    Properties:
      BodyS3Location:
        Bucket: !Ref CodeBucketName
        Key: !Ref SwaggerKey

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref Api

  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Principal:
            Service:
              - apigateway.amazonaws.com

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref Api
      DeploymentId: !Ref ApiDeployment
      StageName: prod
      Variables:
        ApiRoleName: !Ref ApiRole
        ExampleGetFunctionName: !Ref ExampleGetFunction
        ExamplePostFunctionName: !Ref ExamplePostFunction

  ApiExampleGetFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ExampleGetFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref Api
          - "/*/*"

  ApiExamplePostFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ExamplePostFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref Api
          - "/*/*"


  ##########################################################################################
  # Example Get Function -- Handles the example GET request.
  ##########################################################################################
  ExampleGetFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt starterprojectBaseRole.Arn
      Handler: starterproject-Ritvik.handlers.example_get
      Runtime: python3.6
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref CodeKey
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          APP_NAME: !Ref ServiceName
          ENV_TYPE: !Ref EnvironmentType


  ##########################################################################################
  # Example Post Function -- Handles the example POST request.
  ##########################################################################################
  ExamplePostFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt starterprojectBaseRole.Arn
      Handler: starterproject-Ritvik.handlers.example_post
      Runtime: python3.6
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref CodeKey
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          APP_NAME: !Ref ServiceName
          ENV_TYPE: !Ref EnvironmentType
